"""initial

Revision ID: 0f6f95c7bec2
Revises: 
Create Date: 2026-04-21 09:07:23.947340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f6f95c7bec2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bagian_tubuhs',
    sa.Column('id_bagian', sa.String(length=4), nullable=False),
    sa.Column('model_key', sa.String(length=50), nullable=True),
    sa.Column('nama_bagian', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id_bagian')
    )
    op.create_table('latihans',
    sa.Column('id_latihan', sa.String(length=8), nullable=False),
    sa.Column('nama_latihan', sa.String(length=255), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('vas_min', sa.Integer(), nullable=True),
    sa.Column('vas_max', sa.Integer(), nullable=True),
    sa.Column('fase', sa.String(length=4), nullable=True),
    sa.Column('hold_detik', sa.Integer(), nullable=True),
    sa.Column('rest_repetisi_detik', sa.Integer(), nullable=False),
    sa.Column('rest_set_detik', sa.Integer(), nullable=False),
    sa.Column('video_url', sa.String(length=255), nullable=True),
    sa.Column('url_gambar', sa.String(length=255), nullable=True),
    sa.Column('target_set', sa.Integer(), nullable=True),
    sa.Column('target_repetisi', sa.Integer(), nullable=True),
    sa.Column('target_waktu', sa.Float(), nullable=True),
    sa.Column('is_unilateral', sa.Boolean(), nullable=False),
    sa.Column('deskripsi', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_latihan')
    )
    op.create_table('users',
    sa.Column('id_user', sa.String(length=4), nullable=False),
    sa.Column('nama', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('no_telepon', sa.String(length=50), nullable=True),
    sa.Column('verifikasi_status', sa.Integer(), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_user'),
    sa.UniqueConstraint('email')
    )
    op.create_table('kondisi_users',
    sa.Column('id_form', sa.String(length=4), nullable=False),
    sa.Column('id_user', sa.String(length=4), nullable=True),
    sa.Column('id_bagian', sa.String(length=4), nullable=True),
    sa.Column('tingkat_nyeri', sa.Integer(), nullable=True),
    sa.Column('durasi_nyeri_minggu', sa.Integer(), nullable=True),
    sa.Column('has_red_flag', sa.Boolean(), nullable=True),
    sa.Column('red_flag_detail', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_bagian'], ['bagian_tubuhs.id_bagian'], ),
    sa.ForeignKeyConstraint(['id_user'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id_form')
    )
    op.create_table('latihan_bagians',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_latihan', sa.String(length=8), nullable=False),
    sa.Column('id_bagian', sa.String(length=4), nullable=False),
    sa.ForeignKeyConstraint(['id_bagian'], ['bagian_tubuhs.id_bagian'], ),
    sa.ForeignKeyConstraint(['id_latihan'], ['latihans.id_latihan'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_latihan', 'id_bagian', name='uq_latihan_bagian')
    )
    op.create_table('notifikasi',
    sa.Column('id_notifikasi', sa.String(length=4), nullable=False),
    sa.Column('id_user', sa.String(length=4), nullable=True),
    sa.Column('judul', sa.String(length=255), nullable=True),
    sa.Column('pesan', sa.Text(), nullable=True),
    sa.Column('tipe', sa.String(length=50), nullable=True),
    sa.Column('status_baca', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id_notifikasi')
    )
    op.create_table('questions',
    sa.Column('id', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('subtitle', sa.String(length=255), nullable=True),
    sa.Column('multiSelect', sa.Boolean(), nullable=True),
    sa.Column('target_field', sa.String(length=255), nullable=True),
    sa.Column('id_bagian', sa.String(length=4), nullable=True),
    sa.Column('urutan', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_bagian'], ['bagian_tubuhs.id_bagian'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jadwal_latihan_users',
    sa.Column('id_jadwal', sa.String(length=8), nullable=False),
    sa.Column('id_user', sa.String(length=4), nullable=True),
    sa.Column('id_form', sa.String(length=4), nullable=True),
    sa.Column('fase', sa.String(length=4), nullable=True),
    sa.Column('fase_label', sa.String(length=100), nullable=True),
    sa.Column('url_gambar', sa.String(length=255), nullable=True),
    sa.Column('nama_jadwal', sa.String(length=255), nullable=True),
    sa.Column('tanggal', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_form'], ['kondisi_users.id_form'], ),
    sa.ForeignKeyConstraint(['id_user'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id_jadwal')
    )
    op.create_table('question_options',
    sa.Column('id', sa.String(length=10), nullable=False),
    sa.Column('question_id', sa.String(length=10), nullable=True),
    sa.Column('nilai', sa.Integer(), nullable=True),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('history_aktifitas',
    sa.Column('id_history', sa.String(length=8), nullable=False),
    sa.Column('id_user', sa.String(length=4), nullable=True),
    sa.Column('id_jadwal', sa.String(length=8), nullable=True),
    sa.Column('tanggal', sa.DateTime(), nullable=True),
    sa.Column('durasi_total', sa.Float(), nullable=True),
    sa.Column('akurasi_total', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('vas_sebelum', sa.Integer(), nullable=True),
    sa.Column('vas_sesudah', sa.Integer(), nullable=True),
    sa.Column('delta_vas', sa.Integer(), nullable=True),
    sa.Column('rekomendasi', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_jadwal'], ['jadwal_latihan_users.id_jadwal'], ),
    sa.ForeignKeyConstraint(['id_user'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id_history')
    )
    op.create_table('jadwal_latihan_details',
    sa.Column('id_detail', sa.String(length=8), nullable=False),
    sa.Column('id_jadwal', sa.String(length=8), nullable=True),
    sa.Column('id_latihan', sa.String(length=8), nullable=True),
    sa.Column('sisi', sa.String(length=10), nullable=True),
    sa.Column('urutan', sa.Integer(), nullable=True),
    sa.Column('status_eksekusi', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_jadwal'], ['jadwal_latihan_users.id_jadwal'], ),
    sa.ForeignKeyConstraint(['id_latihan'], ['latihans.id_latihan'], ),
    sa.PrimaryKeyConstraint('id_detail')
    )
    op.create_table('history_aktifitas_details',
    sa.Column('id_history_detail', sa.String(length=8), nullable=False),
    sa.Column('id_history', sa.String(length=8), nullable=True),
    sa.Column('id_latihan', sa.String(length=8), nullable=True),
    sa.Column('sisi', sa.String(length=10), nullable=True),
    sa.Column('repetisi_tercapai', sa.Integer(), nullable=True),
    sa.Column('akurasi_latihan', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['id_history'], ['history_aktifitas.id_history'], ),
    sa.ForeignKeyConstraint(['id_latihan'], ['latihans.id_latihan'], ),
    sa.PrimaryKeyConstraint('id_history_detail')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('history_aktifitas_details')
    op.drop_table('jadwal_latihan_details')
    op.drop_table('history_aktifitas')
    op.drop_table('question_options')
    op.drop_table('jadwal_latihan_users')
    op.drop_table('questions')
    op.drop_table('notifikasi')
    op.drop_table('latihan_bagians')
    op.drop_table('kondisi_users')
    op.drop_table('users')
    op.drop_table('latihans')
    op.drop_table('bagian_tubuhs')
    # ### end Alembic commands ###
