"""update latihan bagian structure

Revision ID: c4b7c0b6895b
Revises: c4c7da02e7e6
Create Date: 2026-05-11 05:01:41.395504

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c4b7c0b6895b'
down_revision = 'c4c7da02e7e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('latihan_rule_bagian', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('id'))
        batch_op.drop_index(batch_op.f('id_latihan'))

    op.drop_table('latihan_rule_bagian')
    with op.batch_alter_table('history_aktifitas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('action_result', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('decision_flag', sa.String(length=50), nullable=True))
        batch_op.drop_column('created_at')

    with op.batch_alter_table('jadwal_latihan_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_target_repetisi', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('current_target_set', sa.Integer(), nullable=True))

    with op.batch_alter_table('jadwal_latihan_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('screening_stage', sa.Integer(), nullable=True))
        batch_op.drop_column('created_at')

    with op.batch_alter_table('kondisi_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_session_date', sa.DateTime(), nullable=True))
        batch_op.drop_column('created_at')

    with op.batch_alter_table('latihan_bagians', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_set', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('target_repetisi', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('target_waktu', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('hold_detik', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rest_repetisi_detik', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rest_set_detik', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('progression_repetisi', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('progression_hold', sa.Integer(), nullable=True))
        batch_op.alter_column('id_latihan',
               existing_type=mysql.VARCHAR(length=8),
               nullable=True)
        batch_op.alter_column('id_bagian',
               existing_type=mysql.VARCHAR(length=4),
               nullable=True)

    with op.batch_alter_table('latihans', schema=None) as batch_op:
        batch_op.alter_column('is_unilateral',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
        batch_op.drop_column('created_at')

    with op.batch_alter_table('rehab_rule_bagian', schema=None) as batch_op:
        batch_op.add_column(sa.Column('progression_interval_session', sa.Integer(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('img_url',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('img_url',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('rehab_rule_bagian', schema=None) as batch_op:
        batch_op.drop_column('progression_interval_session')

    with op.batch_alter_table('latihans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', mysql.DATETIME(), nullable=True))
        batch_op.alter_column('is_unilateral',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)

    with op.batch_alter_table('latihan_bagians', schema=None) as batch_op:
        batch_op.alter_column('id_bagian',
               existing_type=mysql.VARCHAR(length=4),
               nullable=False)
        batch_op.alter_column('id_latihan',
               existing_type=mysql.VARCHAR(length=8),
               nullable=False)
        batch_op.drop_column('progression_hold')
        batch_op.drop_column('progression_repetisi')
        batch_op.drop_column('rest_set_detik')
        batch_op.drop_column('rest_repetisi_detik')
        batch_op.drop_column('hold_detik')
        batch_op.drop_column('target_waktu')
        batch_op.drop_column('target_repetisi')
        batch_op.drop_column('target_set')

    with op.batch_alter_table('kondisi_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', mysql.DATETIME(), nullable=True))
        batch_op.drop_column('last_session_date')
        batch_op.drop_column('session_count')

    with op.batch_alter_table('jadwal_latihan_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', mysql.DATETIME(), nullable=True))
        batch_op.drop_column('screening_stage')

    with op.batch_alter_table('jadwal_latihan_details', schema=None) as batch_op:
        batch_op.drop_column('current_target_set')
        batch_op.drop_column('current_target_repetisi')

    with op.batch_alter_table('history_aktifitas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', mysql.DATETIME(), nullable=True))
        batch_op.drop_column('decision_flag')
        batch_op.drop_column('action_result')

    op.create_table('latihan_rule_bagian',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('id_latihan', mysql.VARCHAR(length=8), nullable=True),
    sa.Column('id_bagian', mysql.VARCHAR(length=4), nullable=True),
    sa.Column('target_set', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('target_repetisi', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('target_waktu', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('hold_detik', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rest_repetisi_detik', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rest_set_detik', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_bagian'], ['bagian_tubuhs.id_bagian'], name=op.f('latihan_rule_bagian_ibfk_2')),
    sa.ForeignKeyConstraint(['id_latihan'], ['latihans.id_latihan'], name=op.f('latihan_rule_bagian_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('latihan_rule_bagian', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('id_latihan'), ['id_latihan', 'id_bagian'], unique=True)
        batch_op.create_index(batch_op.f('id'), ['id'], unique=True)

    # ### end Alembic commands ###
