"""add notifikasi columns

Revision ID: c4c7da02e7e6
Revises: 0f6f95c7bec2
Create Date: 2026-05-03 06:16:40.453660

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c4c7da02e7e6'
down_revision = '0f6f95c7bec2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('klinis_threshold_bagians', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_threshold_bagian'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'bagian_tubuhs', ['id_bagian'], ['id_bagian'])

    with op.batch_alter_table('notifikasi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jadwal_kirim', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_sent', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('id_jadwal', sa.String(length=8), nullable=True))
        batch_op.create_foreign_key(None, 'jadwal_latihan_users', ['id_jadwal'], ['id_jadwal'])

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=50),
               existing_nullable=True)

    with op.batch_alter_table('rehab_rule_bagian', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_rehab_rule_bagian'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'bagian_tubuhs', ['id_bagian'], ['id_bagian'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rehab_rule_bagian', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_rehab_rule_bagian'), 'bagian_tubuhs', ['id_bagian'], ['id_bagian'], onupdate='CASCADE', ondelete='CASCADE')

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)

    with op.batch_alter_table('notifikasi', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_jadwal')
        batch_op.drop_column('is_sent')
        batch_op.drop_column('jadwal_kirim')

    with op.batch_alter_table('klinis_threshold_bagians', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_threshold_bagian'), 'bagian_tubuhs', ['id_bagian'], ['id_bagian'], onupdate='CASCADE', ondelete='CASCADE')

    # ### end Alembic commands ###
